name: "Create Escrow"
description: "Launch a campaign escrow with provided parameters"
author: "Hu-Fi"
inputs:
  chain_id: { required: true }
  exchange_name: { required: true }
  symbol: { required: true }
  duration: { required: true }
  start_delay: { required: true }
  daily_volume_target: { required: true }
  reward_token: { required: true }
  reward_amount: { required: true }
  exchange_oracle_address: { required: true }
  recording_oracle_address: { required: true }
  reputation_oracle_address: { required: true }
  gas_warn_threshold: { required: true }

outputs:
  escrow_address:
    description: "The address of the created escrow contract"
    value: ${{ steps.launch.outputs.escrow_address }}

runs:
  using: "composite"
  steps:
    - name: Prepare action configuration
      id: prepare_config
      shell: bash
      run: |
        NODE_VERSION=$(cat "${{ github.action_path }}/.nvmrc")
        echo "node_version=$NODE_VERSION" >> "$GITHUB_OUTPUT"

        YARN_LOCK_HASH=$(sha256sum "${{ github.action_path }}/yarn.lock" | awk '{print $1}')
        echo "yarn_lock_hash=$YARN_LOCK_HASH" >> "$GITHUB_OUTPUT"

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.prepare_config.outputs.node_version }}
        # Since it's composite action and paths resolved in a different way
        # we have to cache manually
        cache: ""

    - name: Install Corepack
      shell: bash
      run: npm install -g corepack

    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ${{ github.action_path }}/node_modules
        key: ${{ runner.os }}-action-deps-${{ steps.prepare_config.outputs.yarn_lock_hash }}

    - name: Install action dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: yarn install --immutable

    - name: Run launch-campaign script
      id: launch
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        WEB3_RPC_URL: ${{ env.WEB3_RPC_URL }}
        WEB3_PRIVATE_KEY: ${{ env.WEB3_PRIVATE_KEY }}
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        CHAIN_ID: ${{ inputs.chain_id }}
        EXCHANGE_NAME: ${{ inputs.exchange_name }}
        SYMBOL: ${{ inputs.symbol }}
        DURATION: ${{ inputs.duration }}
        START_DELAY: ${{ inputs.start_delay }}
        DAILY_VOLUME_TARGET: ${{ inputs.daily_volume_target }}
        REWARD_TOKEN: ${{ inputs.reward_token }}
        REWARD_AMOUNT: ${{ inputs.reward_amount }}
        EXCHANGE_ORACLE_ADDRESS: ${{ inputs.exchange_oracle_address }}
        RECORDING_ORACLE_ADDRESS: ${{ inputs.recording_oracle_address }}
        REPUTATION_ORACLE_ADDRESS: ${{ inputs.reputation_oracle_address }}
        GAS_WARN_THRESHOLD: ${{ inputs.gas_warn_threshold }}
      run: |
        ESCROW_ADDRESS=$(yarn launch-campaign | tail -n 1 | awk '{print $NF}')
        echo "escrow_address=$ESCROW_ADDRESS" >> "$GITHUB_OUTPUT"
