name: Launch Campaign Example

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:
    inputs:
      symbol:
        description: "Trading pair symbol (e.g., HMT/USDT)"
        required: true
      exchange_name:
        description: "Exchange name (e.g., mexc, bybit)"
        required: true
      reward_amount:
        description: "Amount of reward tokens"
        required: true
      daily_volume_target:
        description: "Daily volume target"
        required: true

jobs:
  launch-campaign:
    runs-on: ubuntu-latest
    steps:
      - name: Launch campaign
        id: launch_campaign
        uses: Hu-Fi/campaign-launcher-action@<VERSION_PLACEHOLDER>
        with:
          exchange_name: ${{ github.event.inputs.exchange_name || 'mexc' }}
          symbol: ${{ github.event.inputs.symbol || 'HMT/USDT' }}
          duration: "24"
          start_delay: "0"
          daily_volume_target: ${{ github.event.inputs.daily_volume_target || '100000' }}
          reward_token: "USDT"
          reward_amount: ${{ github.event.inputs.reward_amount || '10' }}
          exchange_oracle_address: "0x1234567890123456789012345678901234567890"
          recording_oracle_address: "0x2234567890123456789012345678901234567890"
          reputation_oracle_address: "0x3234567890123456789012345678901234567890"
        env:
          WEB3_RPC_URL: ${{ secrets.WEB3_RPC_URL }}
          WEB3_PRIVATE_KEY: ${{ secrets.WEB3_PRIVATE_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Display escrow address
        run: |
          echo "✅ Escrow created successfully!"
          echo "📍 Escrow address: ${{ steps.launch_campaign.outputs.escrow_address }}"
          echo ""
          echo "You can view it on the blockchain explorer"
