name: Cancel Escrow

on:
  workflow_dispatch:
    inputs:
      escrow_address:
        description: "Escrow Address"
        required: true
jobs:
  cancel-escrow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Cancel Escrow
        run: npm run cancel-escrow
        env:
          # Input environment variables
          ESCROW_ADDRESS: ${{ github.event.inputs.escrow_address }}
          # Secret environment variables
          WEB3_RPC_URL: ${{ secrets.WEB3_RPC_URL }}
          WEB3_PRIVATE_KEY: ${{ secrets.WEB3_PRIVATE_KEY }}
